export const CONFERENCE_ATTENDANCE_ERROR_CODES = {
  TOKEN_MISSING: "TOKEN_MISSING",
  TOKEN_INVALID: "TOKEN_INVALID",
  EVENT_PASSED: "EVENT_PASSED",
  UNKNOWN: "UNKNOWN",
} as const;

export type ConferenceAttendanceErrorCode =
  (typeof CONFERENCE_ATTENDANCE_ERROR_CODES)[keyof typeof CONFERENCE_ATTENDANCE_ERROR_CODES];
