/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | "Pacific/Midway"
  | "Pacific/Niue"
  | "Pacific/Honolulu"
  | "Pacific/Rarotonga"
  | "America/Anchorage"
  | "Pacific/Gambier"
  | "America/Los_Angeles"
  | "America/Tijuana"
  | "America/Denver"
  | "America/Phoenix"
  | "America/Chicago"
  | "America/Guatemala"
  | "America/New_York"
  | "America/Bogota"
  | "America/Caracas"
  | "America/Santiago"
  | "America/Buenos_Aires"
  | "America/Sao_Paulo"
  | "Atlantic/South_Georgia"
  | "Atlantic/Azores"
  | "Atlantic/Cape_Verde"
  | "Europe/London"
  | "Europe/Berlin"
  | "Africa/Lagos"
  | "Europe/Athens"
  | "Africa/Cairo"
  | "Europe/Moscow"
  | "Asia/Riyadh"
  | "Asia/Dubai"
  | "Asia/Baku"
  | "Asia/Karachi"
  | "Asia/Tashkent"
  | "Asia/Calcutta"
  | "Asia/Dhaka"
  | "Asia/Almaty"
  | "Asia/Jakarta"
  | "Asia/Bangkok"
  | "Asia/Shanghai"
  | "Asia/Singapore"
  | "Asia/Tokyo"
  | "Asia/Seoul"
  | "Australia/Brisbane"
  | "Australia/Sydney"
  | "Pacific/Guam"
  | "Pacific/Noumea"
  | "Pacific/Auckland"
  | "Pacific/Fiji";

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    "operations-media": OperationsMedia;
    editions: Edition;
    events: Event;
    "conference-registrations": ConferenceRegistration;
    "datathon-registrations": DatathonRegistration;
    "nextgen-registrations": NextgenRegistration;
    schedules: Schedule;
    speakers: Speaker;
    ambassadors: Ambassador;
    sponsors: Sponsor;
    exports: Export;
    imports: Import;
    "payload-kv": PayloadKv;
    "payload-jobs": PayloadJob;
    "payload-locked-documents": PayloadLockedDocument;
    "payload-preferences": PayloadPreference;
    "payload-migrations": PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    "operations-media":
      | OperationsMediaSelect<false>
      | OperationsMediaSelect<true>;
    editions: EditionsSelect<false> | EditionsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    "conference-registrations":
      | ConferenceRegistrationsSelect<false>
      | ConferenceRegistrationsSelect<true>;
    "datathon-registrations":
      | DatathonRegistrationsSelect<false>
      | DatathonRegistrationsSelect<true>;
    "nextgen-registrations":
      | NextgenRegistrationsSelect<false>
      | NextgenRegistrationsSelect<true>;
    schedules: SchedulesSelect<false> | SchedulesSelect<true>;
    speakers: SpeakersSelect<false> | SpeakersSelect<true>;
    ambassadors: AmbassadorsSelect<false> | AmbassadorsSelect<true>;
    sponsors: SponsorsSelect<false> | SponsorsSelect<true>;
    exports: ExportsSelect<false> | ExportsSelect<true>;
    imports: ImportsSelect<false> | ImportsSelect<true>;
    "payload-kv": PayloadKvSelect<false> | PayloadKvSelect<true>;
    "payload-jobs": PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    "payload-locked-documents":
      | PayloadLockedDocumentsSelect<false>
      | PayloadLockedDocumentsSelect<true>;
    "payload-preferences":
      | PayloadPreferencesSelect<false>
      | PayloadPreferencesSelect<true>;
    "payload-migrations":
      | PayloadMigrationsSelect<false>
      | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    | ("false" | "none" | "null")
    | false
    | null
    | ("en" | "es")
    | ("en" | "es")[];
  globals: {};
  globalsSelect: {};
  locale: "en" | "es";
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      "conference-registration-confirmation": TaskConferenceRegistrationConfirmation;
      "conference-registration-reminder": TaskConferenceRegistrationReminder;
      createCollectionExport: TaskCreateCollectionExport;
      createCollectionImport: TaskCreateCollectionImport;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role?: ("admin" | "editor" | "viewer") | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: "users";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "operations-media".
 */
export interface OperationsMedia {
  id: number;
  alt?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "editions".
 */
export interface Edition {
  id: number;
  title: string;
  description: string;
  year: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  edition: number | Edition;
  type: "conference" | "nextgen" | "datathon";
  title: string;
  description: string;
  requirements?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  location: string;
  date: string;
  date_tz: SupportedTimezones;
  duration: number;
  durationUnit: "minutes" | "hours" | "days";
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conference-registrations".
 */
export interface ConferenceRegistration {
  id: number;
  event: number | Event;
  firstName: string;
  lastName: string;
  email: string;
  phoneNumber: string;
  participantType: "student" | "professional";
  universityName?: string | null;
  major?: string | null;
  organizationName?: string | null;
  jobTitle?: string | null;
  attendanceMode: "in-person" | "virtual";
  receiveNotifications?: boolean | null;
  acceptedTerms: boolean;
  heardAboutEvent:
    | "friend"
    | "flyer"
    | "social-media"
    | "email"
    | "website"
    | "university"
    | "workplace"
    | "other";
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "datathon-registrations".
 */
export interface DatathonRegistration {
  id: number;
  event: number | Event;
  teamName: string;
  memberCount: number;
  members: {
    isLeader?: boolean | null;
    firstName: string;
    lastName: string;
    sex: "female" | "male";
    email: string;
    phoneNumber: string;
    universityName: string;
    major: string;
    year: "freshman" | "sophomore" | "junior" | "senior" | "graduate" | "other";
    id?: string | null;
  }[];
  bankVoucher: number | OperationsMedia;
  receiveNotifications?: boolean | null;
  acceptedTerms: boolean;
  heardAboutEvent:
    | "friend"
    | "flyer"
    | "social-media"
    | "email"
    | "website"
    | "university"
    | "workplace"
    | "other";
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nextgen-registrations".
 */
export interface NextgenRegistration {
  id: number;
  event: number | Event;
  affiliation: string;
  affiliationCity: string;
  email: string;
  phoneNumber: string;
  expectedAttendees: number;
  receiveNotifications?: boolean | null;
  acceptedTerms: boolean;
  heardAboutEvent:
    | "friend"
    | "flyer"
    | "social-media"
    | "email"
    | "website"
    | "university"
    | "workplace"
    | "other";
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedules".
 */
export interface Schedule {
  id: number;
  event: number | Event;
  type: "activity" | "talk" | "workshop";
  title: string;
  description?: string | null;
  speaker?: (number | null) | Speaker;
  startTime: string;
  startTime_tz: SupportedTimezones;
  duration: number;
  durationUnit: "minutes" | "hours";
  location: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speakers".
 */
export interface Speaker {
  id: number;
  name: string;
  title: string;
  affiliation: string;
  photo: number | Media;
  about: string;
  linkedin?: string | null;
  event: number | Event;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ambassadors".
 */
export interface Ambassador {
  id: number;
  name: string;
  role: "ambassador" | "co-ambassador";
  title: string;
  affiliation: string;
  photo: number | Media;
  about: string;
  linkedin?: string | null;
  edition: number | Edition;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors".
 */
export interface Sponsor {
  id: number;
  name: string;
  logo: number | Media;
  website?: string | null;
  tier: "platinum" | "gold" | "silver" | "bronze";
  edition: number | Edition;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports".
 */
export interface Export {
  id: number;
  name?: string | null;
  format: "csv" | "json";
  limit?: number | null;
  page?: number | null;
  sort?: string | null;
  sortOrder?: ("asc" | "desc") | null;
  locale?: ("all" | "en" | "es") | null;
  drafts?: ("yes" | "no") | null;
  selectionToUse?: ("currentSelection" | "currentFilters" | "all") | null;
  fields?: string[] | null;
  collectionSlug: string;
  where?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports".
 */
export interface Import {
  id: number;
  collectionSlug: string;
  importMode?: ("create" | "update" | "upsert") | null;
  matchField?: string | null;
  status?: ("pending" | "completed" | "partial" | "failed") | null;
  summary?: {
    imported?: number | null;
    updated?: number | null;
    total?: number | null;
    issues?: number | null;
    issueDetails?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug:
          | "inline"
          | "conference-registration-confirmation"
          | "conference-registration-reminder"
          | "createCollectionExport"
          | "createCollectionImport";
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: "failed" | "succeeded";
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?:
    | (
        | "inline"
        | "conference-registration-confirmation"
        | "conference-registration-reminder"
        | "createCollectionExport"
        | "createCollectionImport"
      )
    | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: "users";
        value: number | User;
      } | null)
    | ({
        relationTo: "media";
        value: number | Media;
      } | null)
    | ({
        relationTo: "operations-media";
        value: number | OperationsMedia;
      } | null)
    | ({
        relationTo: "editions";
        value: number | Edition;
      } | null)
    | ({
        relationTo: "events";
        value: number | Event;
      } | null)
    | ({
        relationTo: "conference-registrations";
        value: number | ConferenceRegistration;
      } | null)
    | ({
        relationTo: "datathon-registrations";
        value: number | DatathonRegistration;
      } | null)
    | ({
        relationTo: "nextgen-registrations";
        value: number | NextgenRegistration;
      } | null)
    | ({
        relationTo: "schedules";
        value: number | Schedule;
      } | null)
    | ({
        relationTo: "speakers";
        value: number | Speaker;
      } | null)
    | ({
        relationTo: "ambassadors";
        value: number | Ambassador;
      } | null)
    | ({
        relationTo: "sponsors";
        value: number | Sponsor;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: "users";
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: "users";
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "operations-media_select".
 */
export interface OperationsMediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "editions_select".
 */
export interface EditionsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  year?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  edition?: T;
  type?: T;
  title?: T;
  description?: T;
  requirements?:
    | T
    | {
        text?: T;
        id?: T;
      };
  location?: T;
  date?: T;
  date_tz?: T;
  duration?: T;
  durationUnit?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conference-registrations_select".
 */
export interface ConferenceRegistrationsSelect<T extends boolean = true> {
  event?: T;
  firstName?: T;
  lastName?: T;
  email?: T;
  phoneNumber?: T;
  participantType?: T;
  universityName?: T;
  major?: T;
  organizationName?: T;
  jobTitle?: T;
  attendanceMode?: T;
  receiveNotifications?: T;
  acceptedTerms?: T;
  heardAboutEvent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "datathon-registrations_select".
 */
export interface DatathonRegistrationsSelect<T extends boolean = true> {
  event?: T;
  teamName?: T;
  memberCount?: T;
  members?:
    | T
    | {
        isLeader?: T;
        firstName?: T;
        lastName?: T;
        sex?: T;
        email?: T;
        phoneNumber?: T;
        universityName?: T;
        major?: T;
        year?: T;
        id?: T;
      };
  bankVoucher?: T;
  receiveNotifications?: T;
  acceptedTerms?: T;
  heardAboutEvent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nextgen-registrations_select".
 */
export interface NextgenRegistrationsSelect<T extends boolean = true> {
  event?: T;
  affiliation?: T;
  affiliationCity?: T;
  email?: T;
  phoneNumber?: T;
  expectedAttendees?: T;
  receiveNotifications?: T;
  acceptedTerms?: T;
  heardAboutEvent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedules_select".
 */
export interface SchedulesSelect<T extends boolean = true> {
  event?: T;
  type?: T;
  title?: T;
  description?: T;
  speaker?: T;
  startTime?: T;
  startTime_tz?: T;
  duration?: T;
  durationUnit?: T;
  location?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speakers_select".
 */
export interface SpeakersSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  affiliation?: T;
  photo?: T;
  about?: T;
  linkedin?: T;
  event?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ambassadors_select".
 */
export interface AmbassadorsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  title?: T;
  affiliation?: T;
  photo?: T;
  about?: T;
  linkedin?: T;
  edition?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors_select".
 */
export interface SponsorsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  website?: T;
  tier?: T;
  edition?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports_select".
 */
export interface ExportsSelect<T extends boolean = true> {
  name?: T;
  format?: T;
  limit?: T;
  page?: T;
  sort?: T;
  sortOrder?: T;
  locale?: T;
  drafts?: T;
  selectionToUse?: T;
  fields?: T;
  collectionSlug?: T;
  where?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports_select".
 */
export interface ImportsSelect<T extends boolean = true> {
  collectionSlug?: T;
  importMode?: T;
  matchField?: T;
  status?: T;
  summary?:
    | T
    | {
        imported?: T;
        updated?: T;
        total?: T;
        issues?: T;
        issueDetails?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: "full";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskConference-registration-confirmation".
 */
export interface TaskConferenceRegistrationConfirmation {
  input: {
    "registration-id": number;
    "event-id": number;
    locale: string;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskConference-registration-reminder".
 */
export interface TaskConferenceRegistrationReminder {
  input: {
    "registration-id": number;
    "event-id": number;
    locale: string;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionExport".
 */
export interface TaskCreateCollectionExport {
  input: {
    id: string;
    name: string;
    batchSize?: number | null;
    collectionSlug:
      | "users"
      | "media"
      | "operations-media"
      | "editions"
      | "events"
      | "conference-registrations"
      | "datathon-registrations"
      | "nextgen-registrations"
      | "schedules"
      | "speakers"
      | "ambassadors"
      | "sponsors"
      | "exports"
      | "imports";
    drafts?: ("yes" | "no") | null;
    exportCollection: string;
    fields?: string[] | null;
    format: "csv" | "json";
    limit?: number | null;
    locale?: string | null;
    maxLimit?: number | null;
    page?: number | null;
    sort?: string | null;
    userCollection?: string | null;
    userID?: string | null;
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionImport".
 */
export interface TaskCreateCollectionImport {
  input: {
    importId: string;
    importCollection: string;
    userID?: string | null;
    userCollection?: string | null;
    batchSize?: number | null;
    debug?: boolean | null;
    defaultVersionStatus?: ("draft" | "published") | null;
    maxLimit?: number | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

declare module "payload" {
  export interface GeneratedTypes extends Config {}
}
